const PRODUCTS = [
    {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    },
    {
    id: 2,
    title: "iPhone X",
    description: "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    },
    {
    id: 3,
    title: "Samsung Universe 9",
    description: "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    rating: 3.09,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    },
    {
    id: 4,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    rating: 2.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    },
    {
    id: 5,
    title: "Huawei P30",
    description: "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    },
    {
    id: 6,
    title: "MacBook Pro",
    description: "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    rating: 5,
    stock: 83,
    brand: "Apple",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    }
];